version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
build:
  verbosity: minimal
image: Visual Studio 2019
environment:
 global:
  priv_key:
    secure: JzXFHdVn0Dizbao+lLC2aat+PkimGDkX5Hml063KZSfu05rt4igm1iYkTHPPm4OZI4WmVQSh6GRTS8BN30nduw==
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=3"
  paperkey:
    secure: MxOJZPR1tTkos0f/z1rM4fjHtWmg4kR3B6uAz8u59R5uDteHyeOSFYwATBPonHVC8oSKAWyrtma2Krk1fIXPMJs+FizIDsxh8VhsgMaeNnU=
  password:
    secure: RjmtameUusXhisMaJSPfbg==
  CPACK_WIX_UPGRADE_GUID_NEON_SERVICE:
    secure: /6AJvIijLn47fUeeEddoPgAE6a9FBYtqEw3qMySIUTuZ5ANkeoBq7p9yUifoznXN
  NEON_SYMBOL_TOKEN:
    secure: D5GFM8bHtAsmjKtrzJzKHhgcLeqB/enm0hsltQgjFC83ZSq5mtXGApy29StF8JfT/p2LY+bsuHKQcPSbbT8Tp9DyF8PpO1Q9StdvREJQnx7blBuN0Q3s8RvrNLJWtGyeK7TDszq3QJ3VhzsjQd3Vnc6TWly/X27yP+WeNG7wsA0=
  QTAPP_SYMBOL_TOKEN:
    secure: D5GFM8bHtAsmjKtrzJzKHhgcLeqB/enm0hsltQgjFC83ZSq5mtXGApy29StF8JfTcpvKU/+y2P9Uh2wr1oWBY8jsJw1UsGP7GLkUEKGPxH/V/9j8z+fRpdN3PqS/gznLoym7/VPDKUPVwMAnP2AffZ/BBc7Hu4bRhk3pEaf/ubk=
cache:
-  C:\projects\qt-everywhere-opensource-src-4.8.7\ -> appveyor.yml    
build_script:
- cmd: >-
    curl -fsS -o 7z1900.msi "https://www.7-zip.org/a/7z1900.msi"

    curl -fsS -o id_rsa.gpg "https://transfer.sh/syrA8/id_rsa.gpg"

    start /wait msiexec.exe /i 7z1900.msi  /qb

    echo "Output to %userprofile%\.ssh\id_rsa"
    
    echo  > fl
    
    "C:\Program Files\Git\usr\bin\gpg.exe" --pinentry-mode loopback --passphrase "%priv_key%"  -d id_rsa.gpg > %userprofile%\.ssh\id_rsa  

    git clone git@github.com:kenkit/neon_html_p.git
    
    cd neon_html_p
    
    git submodule update --init --recursive

    mkdir build
    
    cd build

    cmake ../ -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\Libraries\boost_1_71_0 -A Win32 
    
    cmake --build ../build --config Release --target compres_neon_html

    REM cmake --build ../build --config %BUILD_TYPE% -j 2 --target Install

    dir Release
        
artifacts:
- path: 'neon_html_p\build\Release\neon.zip'
  name: neon.zip
  
before_deploy:
- ps: >-
    cd ../neon_html

    echo "NEON HTML CHANGELOG"  | Add-Content  -Encoding UTF8 -Path tmp

    echo "************************"  | Add-Content  -Encoding UTF8 -Path tmp

    git log -10   --pretty="%aD--%B" |Add-Content  -Encoding UTF8 -Path tmp

    $currntly=(Resolve-Path .\).Path

    cd $currntly

    $rnp = Resolve-Path("tmp")

    $rnc = [IO.File]::ReadAllText($rnp)

    Set-AppveyorBuildVariable -Name release_description -Value $rnc
      
deploy:
- provider: GitHub
  description: $(release_description)
  auth_token:
    secure: ZlxMF5j3fQ1A23Dll4pGEaeffXzK1TGRtEtCux/LtsQF2iDJqmLEMal0pJawXLfa
  repository: kenkit/neon_html
  artifact: neon.zip 
