version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
build:
  verbosity: minimal
image: Visual Studio 2017
environment:
 global:
  priv_key:
    secure: 24BDMoF4u8ToRnImbhwtMf2qFKrqPwnD0i7Q3nq/oISIGJYviTIPFm++u+ktPKcftazo2jogZkbRsboUz0VCsvNZKVD/KGsHrRjoD8nUbFOekH/HuEpNm6iU4zW5TQilMQAbYKeqiyC5pmWRAXCrI4UzJWSG6ZX4f2RSz3dHae3Fpj/zdXBzaLSqLUI/0d/u/k7fekCVI5qWXL8ecO6zWlDA4EAo+0/p02Gbsnb3QWlNWmZpDKUDJ9AznBhqOFaqxaB41r5/lz6uXdijyCRBaozV6f5jPchX6XDQtnPiQD7JnPGR1BNGx//9DJgrMmUiuFBLVzXCkTc9lwWohisopl2WVFWk3gJXmzrUbsqKRUe1raxuBOp9KUNOH3KcWAkaZiIjmRw0/JXW1BVLE9Nkkjiw2wYgOiWH1L9XeIxpiRryvDGbkW1w9DpeTVJjXyp6yYTi5UG7L6rJLRKS0di11ruzIcsziRnshX6vQa9kXxv29bbXKmJqnMKX7u+miWdyl7715ocLMpp7zcuYd6naJV6/Pm835K064793L0Fgfzsn4HbE9h+mft8TKWN5Zj9dTU+oORnUcWeKqDX1omyG+kFRsUhiBPMN7jLnUicn+O8y6nkxnv6zd0pPsGHA9E8kL9zIVR0BokY4ify2HFmkueFvvLsgOQAobXkho3OjeAMcNAZ7hnluVJerk/Ry96kVBRfY82WJdqCuruMJvoAAFonigyRuY6mWMkLkD8KTg2uTj9kuuIIdce0Le1k6nZbSc30zUz7SHQrw/tXfBT5/ZRWeCMbySQkP7aaiapgFgjZupfpvPVawMyXl/ziMsx2Snr7BsvZUnsjNRY5Zr2QboQJ+IDz4V1eVgeW1MEBnOgTYpVS7NmMzUtvtESm0RrEF9Ge+7kRQnPOP1jfr5j+eU4ENhFge2oNO45HJNCobT0eSc/fb92c8AGabrm5wChy95CLe9MpPdScjna6g57e1rflPhHS8luNejviDYsKo/Z/oO6S4pxBMbOsY9PmjSxYG3UNZeEu5Dk8jio4IvN9I/+pDZajEr98sEluHsQ/2U0bjaxxFCSBf9UBGd0pvvI+EyY9vKn83VfNAtiMwAXxnIgf32d85WW5MjXCkvPwvsGi31JUl3URFVAqd7D7B5+ACF6X89uUyqfRE+6S7UubuKC4iUPhOaHf/3HY140Vgf06fGpQGm5+L7uBtgQaFkijkTYzpLPcZA78z446cD/7eTSnQJTjZh0FXt/CwZYvocSKDbW+BSgnccLsUi4bOcASFdrMTxDlUQvd+i+PENUKl5buce4XV4czufUVvqvmuttd08cZYI0TfnORKrRjkCdXj7aJTy/xJzA9lNSjWg3M+T2rJ0BsjQefHeYUQiSNQCyFJ4LQu0+B+/B9+BdzktXjhMAJhEONvKOXNd9h16cTJ/Qouctt+qgQqWCD1CTrnlqa3/E1275b4K0qSETq+6uf8MnNB36UxdKpUwPH0FfyfFJz1257E3UJ+88VlKqWy4tc3zdIp/CuNl0RSIUlytBNqZ4EeaG+rdUQhZz1N+Er4toitGbAFAtXPiIT/RpjxBOf3GYKMFW1a6H17O30SeAJ/f+4ZbWwLoWdaFyj8CBMrHNVwQVTzNohCbD6tMeiXn68h0OR406OcYI2BNps4iaPMHZGoqOqyMhAGfeI9rZAAYsfhu/CYlYNn8f6oAYERoDkvKeivi+bx0On+LvrMxpP2jathe4URtte/ZStY3pM268zIXH1r6H6PL/VuVuxnNsGvPHKK12JK3bEpFIfaJtsenY/LcqYkXXAZubMuuT4m66X8H1qT6zaBi9nntHBAImP322SUlMVioZ/K0vm6Dz/66P0jmAdGBghO52GPlIkUb14ANXQMt2Muxr6GRXv1yW8BmVBvdZ/38xqe30rWtGd2P0BBMyI2dDQ1TFQ5Vr5vkyGSXSFvp6IVtLUmS5e45gZ1nBKj0kGOOScR9vSXwpNAWVfPRa6MiNgFCl1rHapLfmVfaYZnkFdlPm+2SWjlqiwXRp57BJoC69y8XpVZJQ34Hr7A3DI76CskQfY83rA4A/HYblpw2Mpl66MhodlJSwoKRd9924KBjkw7LmqNtc5UqEziaCs90DgfYCP2Gew+2IoFssmozs5QAGPyGvSSUb59nJBxgqdPw9B6waDOUu89xl20gBgGZd+gCIVktNAYj1syqP27H2uGNceeZ5/0O5AUz7ha0ykZApeEE2bx8d2gur89hoTGCN+YSW5wJoeIB4imPv2V6SbnzV0NbcpVgz/bLr8JjIhCxVQxMe/11nssQk1wkmTWGWNGOVgIvx4wh2k6oSu+Jvz0cCwA8K65JXsNxQuuWrlmYLDyHPg/34SG+aWZXM6sT5BR8wlbj7VKef7so9Bi4tZt2NdnXHYLjOdjZtUXb4DtCOtDNdUUYxNvHmbnCMaahXdcHDCUYy7GZe2Ra9efphXg5osmjmQeC2lpoo8B6FR5nJYAV6lqhnaU+VSkDMxjbEZqDnLQ8ITOSDxZQumgcQnJveYqqOeqbLwu6PVUtThXjI3fsbJNORmbd6rLKoDePqNO8iCEbKxyKG0J7Cdwwg3T/xtQqpFSO68oMGDtuQVPV4wzgzEadypLQzXmjsgW/AtZdCd5ujmVFDYVy/jc72d8SvBcYKtEiAxmNf5nFXssBMkcRKT1CD/+Y2AraXCK/247IYZjKHIj8hmTNr5B56e1MWhg7rj8SDarQh/H5iXqVk4hPlVl0F4tvFa9EguOg6hPHwqTAqc7yq3CWb5qTkDEBgw98O7eS+7SdGqvRnvq9jrXB3rgfdFyoAEFc3VVSgBe1IO6RqsnSreJrMNfPaw/+CRrsrimRG0NNzaKE+6M2BV0fWY7tq0rcngIaNvT+aogM7jGAHEPYWRe3aMziLdYdIU3SxjwqZP/ntg8PqXsjHri/EWAqvANWRSyl8JKyP/il269Qp1rXHVAxH/lEfUrKANsSqTBVjLQb4MZBheoeqbyVmXKjh1Hn5/snftfZdvXPu2qZO5f0DeyWp/D/9atBRI1OFY0uT07HmNBPH0HypFbrh8tOPdFgCCXnL9yPWi1rg1z6/a5a/tYktgsk5GZMyCIDo4SRSgdcxaEdgkF7JBORlmufphz7cHYzN6QIZEP4TPowAWmn3r17WAU4YxHAfjBOhFT4iILbsgcnLb9c9r3FCfFqkJL7vJ6Bc4Jy0gnaGqVqZhaVTFnKpGaaV/n2OoLNtVJVz32hYGUYi0y9+IZrkEM8R4lzL3CFNvxVVaI4s89TUM5coAG2kzVlYlZ0STwd58zJISs6MY/FvOGm7tsqWHAV5yO+UbcrLE+tQ1SXW4p+LIAHo8aVq84BBRIO9MFM+CRGzYUk3dFG2NAdhMnlksGDZXZTadYVi9FXxboclK9AEG8JoOMhnbg00WdpiDtZzy2FIE9O1vPaSv/myoYqWa2KYKh3r3dpABDYUEJDZm0OSMyJwMxwdn0wIbEbuzGKhL/DZNwLcadSWGuttlk9esveJ+zqKCTFzLGjQ7R/bkpEu8W52HhRc7T4zQd2IRZ53FfkQPfib76moP94I9JZgdVFNP92ukII6QE4lvRZfaehPMkZ2JC9+RVhPp0ND6A9BJCgJ+7UH4wrJ622xyKAHN6k1B561QlpZzCveBidcsIl5J1czRm1pzR3WqjcJOAmsIhm+CQMlmyLXI09zZ8YAZI9/gHCLLjvTlilmACb8aHwize27ikM8xkhe+cNwkUfldVgTv5i9xGdEgmeQjsMVCWClVUd/ddYHAZXuTkO69MZ78LVOW3UzrGR6KLGK9ltWNF+ksaR8EwgVcy+24NDQJAYN1MW3+1Rcm2rXFMH+1w363aKYuI+m7t2YCdDQXw0cPS454yedBUVOUtD2//zn9LM243q5tuOA1rstZqW84tOwfbTcTfEVPLvDbislO8rjV9+8e3dM5BHQc6C6ncJ3NPqkR4n1glngd+DYLgT1pvTwy55jZQYfFAG4aJavxQ6itZexiyI4dKgSK15BwZGobfYUhHIjVpaeXY5of7WLGSC4MJOucxAnmu33SHDso128g92A7/vgW7yMS/fCo1dKjfa1quBXOuMWptBzYHqh9giCQ4eSd6f9eYz22xvhJmF+xcdgLHnjiba5SdDsyMeIZaDKoRxr7MO6xJBmsNruyaiBYyrehPZDJxq3ueTPFj10ZL4554jKH7FitnzGIEuss4x+I2IVjAFvwEHYDqanMbETuUlqBUSQFAv97fHYPLDRJUah4HcfIhma8xOGg9zgWG2no4XIxu8TwDt8sDFWxOF8wBaP4V8xfj+a/eMY/3A7E3g227l8jgf92OMj6bPfLuBtb3lRPW4dfBWS4UTYlV82EmqGglcPUNvtrLPVL8PSE0cf2C0ysjy0PycaeOFKHsz4vxcK52gGqtDAgiMOq53IzqKpmK4dlpevBm3RJ6PyKboIk=
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=3"
  paperkey:
    secure: MxOJZPR1tTkos0f/z1rM4fjHtWmg4kR3B6uAz8u59R5uDteHyeOSFYwATBPonHVC8oSKAWyrtma2Krk1fIXPMJs+FizIDsxh8VhsgMaeNnU=
  password:
    secure: RjmtameUusXhisMaJSPfbg==
  CPACK_WIX_UPGRADE_GUID_NEON_SERVICE:
    secure: /6AJvIijLn47fUeeEddoPgAE6a9FBYtqEw3qMySIUTuZ5ANkeoBq7p9yUifoznXN
  NEON_SYMBOL_TOKEN:
    secure: D5GFM8bHtAsmjKtrzJzKHhgcLeqB/enm0hsltQgjFC83ZSq5mtXGApy29StF8JfT/p2LY+bsuHKQcPSbbT8Tp9DyF8PpO1Q9StdvREJQnx7blBuN0Q3s8RvrNLJWtGyeK7TDszq3QJ3VhzsjQd3Vnc6TWly/X27yP+WeNG7wsA0=
  QTAPP_SYMBOL_TOKEN:
    secure: D5GFM8bHtAsmjKtrzJzKHhgcLeqB/enm0hsltQgjFC83ZSq5mtXGApy29StF8JfTcpvKU/+y2P9Uh2wr1oWBY8jsJw1UsGP7GLkUEKGPxH/V/9j8z+fRpdN3PqS/gznLoym7/VPDKUPVwMAnP2AffZ/BBc7Hu4bRhk3pEaf/ubk=
cache:
-  C:\projects\qt-everywhere-opensource-src-4.8.7\ -> appveyor.yml    
build_script:
- cmd: >-
    curl -fsS -o keybase_setup_amd64.msi "https://prerelease.keybase.io/keybase_setup_amd64.msi"
    
    start /wait msiexec.exe /i keybase_setup_amd64.msi   /quiet /l*v keybase.log
    
    curl -fsS -o 7z1900.msi "https://www.7-zip.org/a/7z1900.msi"
    
    start /wait msiexec.exe /i 7z1900.msi  /qb

    set PATH=%PATH%;%localappdata%\Keybase\
    
    keybase -v
    
    REM type keybase.log
    
    echo "loging in to keybase"
    
    ping -n 4 127.0.0.1>nul
    
    call keybase oneshot -u kenkit --paperkey "%paperkey%"
    
    set ROOT=%cd%
    
    set OPENSSL_ROOT_DIR=C:\OpenSSL-Win32\
    
    REM cd %ROOT%
    
    git config --global --add protocol.keybase.allow always

    git clone git@github.com:kenkit/neon_html_p.git
    
    cd neon_html_pub
    
    git submodule update --init --recursive

    mkdir build
    
    cd build

    cmake ../ -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\Libraries\boost_1_67_0 
    
    cmake --build ../build --config Release --target compres_neon_html

    REM cmake --build ../build --config %BUILD_TYPE% -j 2 --target Install

    dir Release
        
artifacts:
- path: 'neon_html_pub\build\Release\neon.zip'
  name: neon.zip
  
before_deploy:
- ps: >-
    cd ../neon_html

    echo "NEON HTML CHANGELOG"  | Add-Content  -Encoding UTF8 -Path tmp

    echo "************************"  | Add-Content  -Encoding UTF8 -Path tmp

    git log -10   --pretty="%aD--%B" |Add-Content  -Encoding UTF8 -Path tmp

    $currntly=(Resolve-Path .\).Path

    cd $currntly

    $rnp = Resolve-Path("tmp")

    $rnc = [IO.File]::ReadAllText($rnp)

    Set-AppveyorBuildVariable -Name release_description -Value $rnc
install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent

deploy:
- provider: GitHub
  description: $(release_description)
  auth_token:
    secure: ZlxMF5j3fQ1A23Dll4pGEaeffXzK1TGRtEtCux/LtsQF2iDJqmLEMal0pJawXLfa
  repository: kenkit/neon_html
  artifact: neon.zip
