version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
build:
  verbosity: minimal
image: Visual Studio 2017
environment:
 global:
  priv_key:
    secure: 24BDMoF4u8ToRnImbhwtMf2qFKrqPwnD0i7Q3nq/oISIGJYviTIPFm++u+ktPKcfoEUvQ7omtC0Y8kYaSP0BIdnLgy4215w7sKjAAYA/wDKdzHwzWZH7GOm4lQL8TQRs79IJSjjE5PN3SGcvQCb5D41KmLt2DzlfBXL+5gMLAEIYhEyaS6GNKvL5uIo1HU3RoJAyX2rIVZ0QjfabfsofyPkKcdRFwWKECbI2OPgIQDyvNj8xqZ3DLOHerZqqRMQr/ewF8BIdmqMNLfYX5T/e/vgZyqgoQ/mxvFMLjFCn/xyAoBxoC/MNU1sl73Xb2nEcFhdRCJ4tknezBFXXJ8vD3FWouyQ8d79HMcQeu5tg3/9FTFqwK7hGdtXHbHHqs6ctZsdZf6dW7XC9GywML+p/pD4MJ9wt3hbwgyyzw4ll1+Hf9e2qlBMR76+I7RjRskOgELeKcCU8uChHd7CeP3/M06U8dhct6kVXoH8XY1RHJ7LI7JPnySaRQIDC70nsUWCOWI6wsiNplSgTdLi9sr1OVFkHz8f3I5r87oyqLz3vf01sdmic5xc3Vv4ATdIf7IuV1AydEvCyRE9PW4aeuHcqqGVOYPacaqmmiD+E1C6Yx+27S0Ppr4q6YCBqks1YwjurC0XyKXQrdTtiFPRSFn1QPsKtK5V0UoxNLZA5jeOLJLWcE9Qv/EeesWBibhPl8lLKE0S+K4H6tMibWygK+jDLiyXTonplcFQ3ywQsQo0hvUUlObWwMTh7nm2SsIKkg2hUGvrSFZXX5uOEyEp9+6lqAXCgAQybHpOTCaL2e1iYQCEHGQx3F+Pu67uOg4Qm0Ssqd83T552ut9ztyGVZXNVGihxdK1QXNvwzLIduqq3ALFWf/oQzYfgLAkxFl8/4IzlW0d0jS0s410W80FTaBw3rUUvC8b7YQt/7+BxKLSsXO5+hsTfjxrfOjpf3vAYtFhexPUuATAih+9MizIWA+zQC5mNoVFaVgCPOK4SwreqGwE5YDQvqai4VEuOdjh66nEpUOf9EK5gsXg6xDoxw8bTNE+7iGw2DKnBAen7pmnv/6tKJLGl2UPYrm9jNZOz0KcvGE8jFB8TMSqQD4whkQTNcA2GZ9423L2rZTRMH4DGzldyD8BEJ5233gVXwpR2K+KaGtJuIlRQEwYXKzPri+XUFH50AUPiyeqtZobhq9T9kKBSl7plZsDPcT0Mlt1gSX+QSQ/q4V/5b82hWFbqzwiup3Oq3kdcFc9aAz1sdpSzhCr/jh1BuYPlCmdVpUHY8C+7Q4x0LY1JrzReAJvarrcwmNjmvOhy/5FTk9JCF6furvPbXRvkKOxhFuC69SCaZgDVNXkljIEuqpP9UZOHvtWzzlYNIeiy1SfcfciOIhuFcqUSgrBRq6m7fn4FgH0E8+xmicX6ARTVqjqtjcfHCuP90Aw13SX4/Nc4KLW5//jySbcz0YJrWDTr0TTsWeGK43TPxwdS8+ZjWn4z4SXuaB6dmJMSc/2iAVp14nkdILoEtN84I/dmNe1dPor+DnAcCSwDvk+N42xTcapGOH5+ItfNULAYqnsQw2MS6jcPfIhdXJgLfl+cRsjSGA+KWCAJ0dddCiFtyYrhvWpG9lr8IbXWry8g7eoxSl67/l2R0MLuOAQMtzUvK8VZUtFXcmvoMwSuez+LeJGl4PnQDBBEhsu/KuqJddIpeOwm1c05mbDJjkTcsuK9wsaXhpH9OUg5WFrwi1uB3p4tCfj2rO9eiJSFhZlMT1h0avYhuGg3fiuKYtXGUi5fNdTWVdAxTpJfJRdi6U/o90dVEq4ClnYaqJFoH3iY29VD0Dx/iEG2X7yXIVxiVKMRO2nKhzl8egxwTFz+XxF1WpCCOOhE/gjT0aE3DCu9FKre8isQbuMhkAoIymHt4Oa5m8bhN8sgxzlNBfj1RSKBzrn2H7xogMCQ2blbwdiBTm011EgbDoyM6vUEotT/EGM/jlvTTxJfhi/ZvZ+ERebi5rtk1RQ2Lm+v9CHzkEnoTdjc7a5YBC1fara2QXdbv550uyMje7BxVelFqU/RoR3Vb1J6EdpzFcB/wLxqf0niKxQ8u7T/UlkXWg6kiIYWYl8pivvdyBk9xt5KT0Ir6qaN7MlT57xkgOXyfJaEZzeIWw5o5dChNKgakymKVh5bsGEBFFBKuG4rhhILckeEyxWnjT+ZJdkSdjyy/6InnkU8Gf/z4EmlSQZvAzkbq8Nhh1mze7JJVrAHP+6bdIrCsLcfuQ9FcpcB+WFVjv27FxWOlPvN/1m3J1DyCNXPXkd86ItxYda3/xrCcV1EgwhZaMyMVEpZnAo94SkPh8UOMVFIXQRX91MBPAGX2i+quyJ1RtFOVt+YM7LfkXuBReQJU5VoeXyeikRzY60dT1s3YUthcuVDmK1s7vXIg0J8cA+PDN7wqLhKUZsN0B8/01xVUtAXNUJ6f3KkbAZH4lM4+Alo4ldR38nRR7VDhJBMbewibI4nHh/zADUatnpDeU8+3CWuenugsZ4RjwAJ9bHw4jeVBMjtJQCkpb39jVzqbyUCSm8aXPJtPUcv/lzHSUClhK/9ZfRWf1yJIPixux4lRGaKnUbTL3IO/JtKlDRd7QcDFKTZ3rU4CZIXOi7uBu9ttZU1rWS+4n+cEQeYEQAf0vbIRCAB19d0Q+SuCosGeWlMOGqWmi2Php5RqZVOSJ0nhv73EAIzbgdA8F4/IAjnPe6YNJ51iMMCXBA7hlylpvUBFMPb/mGyHZYtBzTt77gn3V52hpFkWgflUehW7zRJ8yhAV1FTxT/nhrANSDBLkzvxueOw53JK1sOiw7UgoD55pijngROIq7iV9JlDQqj+Tf/ueEU73mnO7uO2P7EA5ZDwwgKtstkEprIuNNZhNe7oakUVX4kuMYt+f0Pfvx/QUPLlZLKsL9AKXccIYiRF7sDpBCGZN8wLBfV9g3n6ZtbQA7AIV9qiMAT1bpyqPLEclR3R/jaxLulKSI1BKtDdGYfOSr3bRqZEO50e3Valyc436/e0IgTL9aRFK0fjcmtXru9xuuNiQeAx7OdTG0HE3FfZnQWa0Iymi52w4+k+zxNVSl8rDKi5S9/bfzY42puxSFBizmb3wVkFvvNXfrLC617/2Gz/KlhpIvvSVzf6qY+i3DJTrAPXsZt7YWqzh5LQK4/Nl7+LIagPowKdmrlW9t3kr7bNNWHSmeR8jrB/ZQYShlwGrASHbLpTYSaVd2FMBtXEEsClMusEoet6KHw5H1kQ2P4+U6vSQd/9MkXZr3kNGVPdOPVqrDPvCta8MMhJ2PiaR63ZxIkVWwDT2rjfMkAxE3flBvnIC/16TY56lVNdc97uwShS/yjSNADER4bUtVMgKcHNvXxMtqJkPJShFvv9jLvoiPVKXiDWHh269PM1J
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=3"
  paperkey:
    secure: MxOJZPR1tTkos0f/z1rM4fjHtWmg4kR3B6uAz8u59R5uDteHyeOSFYwATBPonHVC8oSKAWyrtma2Krk1fIXPMJs+FizIDsxh8VhsgMaeNnU=
  password:
    secure: RjmtameUusXhisMaJSPfbg==
  CPACK_WIX_UPGRADE_GUID_NEON_SERVICE:
    secure: /6AJvIijLn47fUeeEddoPgAE6a9FBYtqEw3qMySIUTuZ5ANkeoBq7p9yUifoznXN
  NEON_SYMBOL_TOKEN:
    secure: D5GFM8bHtAsmjKtrzJzKHhgcLeqB/enm0hsltQgjFC83ZSq5mtXGApy29StF8JfT/p2LY+bsuHKQcPSbbT8Tp9DyF8PpO1Q9StdvREJQnx7blBuN0Q3s8RvrNLJWtGyeK7TDszq3QJ3VhzsjQd3Vnc6TWly/X27yP+WeNG7wsA0=
  QTAPP_SYMBOL_TOKEN:
    secure: D5GFM8bHtAsmjKtrzJzKHhgcLeqB/enm0hsltQgjFC83ZSq5mtXGApy29StF8JfTcpvKU/+y2P9Uh2wr1oWBY8jsJw1UsGP7GLkUEKGPxH/V/9j8z+fRpdN3PqS/gznLoym7/VPDKUPVwMAnP2AffZ/BBc7Hu4bRhk3pEaf/ubk=
cache:
-  C:\projects\qt-everywhere-opensource-src-4.8.7\ -> appveyor.yml    
build_script:
- cmd: >-
    curl -fsS -o keybase_setup_amd64.msi "https://prerelease.keybase.io/keybase_setup_amd64.msi"
    
    start /wait msiexec.exe /i keybase_setup_amd64.msi   /quiet /l*v keybase.log
    
    curl -fsS -o 7z1900.msi "https://www.7-zip.org/a/7z1900.msi"
    
    start /wait msiexec.exe /i 7z1900.msi  /qb

    set PATH=%PATH%;%localappdata%\Keybase\
    
    keybase -v
    
    REM type keybase.log
    
    echo "loging in to keybase"
    
    ping -n 4 127.0.0.1>nul
    
    call keybase oneshot -u kenkit --paperkey "%paperkey%"
    
    keybase fs cp keybase://private/kenkit/id_rsa c:\users\appveyor\.ssh\id_rsa
    
    set ROOT=%cd%
    
    set OPENSSL_ROOT_DIR=C:\OpenSSL-Win32\
    
    REM cd %ROOT%
    
    git config --global --add protocol.keybase.allow always

    git clone git@github.com:kenkit/neon_html_p.git
    
    cd neon_html_pub
    
    git submodule update --init --recursive

    mkdir build
    
    cd build

    cmake ../ -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\Libraries\boost_1_67_0 
    
    cmake --build ../build --config Release --target compres_neon_html

    REM cmake --build ../build --config %BUILD_TYPE% -j 2 --target Install

    dir Release
        
artifacts:
- path: 'neon_html_pub\build\Release\neon.zip'
  name: neon.zip
  
before_deploy:
- ps: >-
    cd ../neon_html

    echo "NEON HTML CHANGELOG"  | Add-Content  -Encoding UTF8 -Path tmp

    echo "************************"  | Add-Content  -Encoding UTF8 -Path tmp

    git log -10   --pretty="%aD--%B" |Add-Content  -Encoding UTF8 -Path tmp

    $currntly=(Resolve-Path .\).Path

    cd $currntly

    $rnp = Resolve-Path("tmp")

    $rnc = [IO.File]::ReadAllText($rnp)

    Set-AppveyorBuildVariable -Name release_description -Value $rnc

deploy:
- provider: GitHub
  description: $(release_description)
  auth_token:
    secure: ZlxMF5j3fQ1A23Dll4pGEaeffXzK1TGRtEtCux/LtsQF2iDJqmLEMal0pJawXLfa
  repository: kenkit/neon_html
  artifact: neon.zip
